//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	url "net/url"
	unsafe "unsafe"

	proxy "github.com/karmada-io/karmada/pkg/apis/proxy"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*GlobalResource)(nil), (*proxy.GlobalResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GlobalResource_To_proxy_GlobalResource(a.(*GlobalResource), b.(*proxy.GlobalResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.GlobalResource)(nil), (*GlobalResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_GlobalResource_To_v1alpha1_GlobalResource(a.(*proxy.GlobalResource), b.(*GlobalResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalResourceList)(nil), (*proxy.GlobalResourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GlobalResourceList_To_proxy_GlobalResourceList(a.(*GlobalResourceList), b.(*proxy.GlobalResourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.GlobalResourceList)(nil), (*GlobalResourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_GlobalResourceList_To_v1alpha1_GlobalResourceList(a.(*proxy.GlobalResourceList), b.(*GlobalResourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalResourceSpec)(nil), (*proxy.GlobalResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GlobalResourceSpec_To_proxy_GlobalResourceSpec(a.(*GlobalResourceSpec), b.(*proxy.GlobalResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.GlobalResourceSpec)(nil), (*GlobalResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_GlobalResourceSpec_To_v1alpha1_GlobalResourceSpec(a.(*proxy.GlobalResourceSpec), b.(*GlobalResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalResourceStatus)(nil), (*proxy.GlobalResourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GlobalResourceStatus_To_proxy_GlobalResourceStatus(a.(*GlobalResourceStatus), b.(*proxy.GlobalResourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.GlobalResourceStatus)(nil), (*GlobalResourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_GlobalResourceStatus_To_v1alpha1_GlobalResourceStatus(a.(*proxy.GlobalResourceStatus), b.(*GlobalResourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxyOptions)(nil), (*proxy.ProxyOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxyOptions_To_proxy_ProxyOptions(a.(*ProxyOptions), b.(*proxy.ProxyOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.ProxyOptions)(nil), (*ProxyOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_ProxyOptions_To_v1alpha1_ProxyOptions(a.(*proxy.ProxyOptions), b.(*ProxyOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceSelector)(nil), (*proxy.ResourceSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceSelector_To_proxy_ResourceSelector(a.(*ResourceSelector), b.(*proxy.ResourceSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.ResourceSelector)(nil), (*ResourceSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_ResourceSelector_To_v1alpha1_ResourceSelector(a.(*proxy.ResourceSelector), b.(*ResourceSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*url.Values)(nil), (*ProxyOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_url_Values_To_v1alpha1_ProxyOptions(a.(*url.Values), b.(*ProxyOptions), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_GlobalResource_To_proxy_GlobalResource(in *GlobalResource, out *proxy.GlobalResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_GlobalResourceSpec_To_proxy_GlobalResourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_GlobalResourceStatus_To_proxy_GlobalResourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_GlobalResource_To_proxy_GlobalResource is an autogenerated conversion function.
func Convert_v1alpha1_GlobalResource_To_proxy_GlobalResource(in *GlobalResource, out *proxy.GlobalResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_GlobalResource_To_proxy_GlobalResource(in, out, s)
}

func autoConvert_proxy_GlobalResource_To_v1alpha1_GlobalResource(in *proxy.GlobalResource, out *GlobalResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_proxy_GlobalResourceSpec_To_v1alpha1_GlobalResourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_proxy_GlobalResourceStatus_To_v1alpha1_GlobalResourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_proxy_GlobalResource_To_v1alpha1_GlobalResource is an autogenerated conversion function.
func Convert_proxy_GlobalResource_To_v1alpha1_GlobalResource(in *proxy.GlobalResource, out *GlobalResource, s conversion.Scope) error {
	return autoConvert_proxy_GlobalResource_To_v1alpha1_GlobalResource(in, out, s)
}

func autoConvert_v1alpha1_GlobalResourceList_To_proxy_GlobalResourceList(in *GlobalResourceList, out *proxy.GlobalResourceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]proxy.GlobalResource)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_GlobalResourceList_To_proxy_GlobalResourceList is an autogenerated conversion function.
func Convert_v1alpha1_GlobalResourceList_To_proxy_GlobalResourceList(in *GlobalResourceList, out *proxy.GlobalResourceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_GlobalResourceList_To_proxy_GlobalResourceList(in, out, s)
}

func autoConvert_proxy_GlobalResourceList_To_v1alpha1_GlobalResourceList(in *proxy.GlobalResourceList, out *GlobalResourceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GlobalResource)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_proxy_GlobalResourceList_To_v1alpha1_GlobalResourceList is an autogenerated conversion function.
func Convert_proxy_GlobalResourceList_To_v1alpha1_GlobalResourceList(in *proxy.GlobalResourceList, out *GlobalResourceList, s conversion.Scope) error {
	return autoConvert_proxy_GlobalResourceList_To_v1alpha1_GlobalResourceList(in, out, s)
}

func autoConvert_v1alpha1_GlobalResourceSpec_To_proxy_GlobalResourceSpec(in *GlobalResourceSpec, out *proxy.GlobalResourceSpec, s conversion.Scope) error {
	out.TargetCluster = in.TargetCluster
	out.ResourceSelectors = *(*[]proxy.ResourceSelector)(unsafe.Pointer(&in.ResourceSelectors))
	return nil
}

// Convert_v1alpha1_GlobalResourceSpec_To_proxy_GlobalResourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_GlobalResourceSpec_To_proxy_GlobalResourceSpec(in *GlobalResourceSpec, out *proxy.GlobalResourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_GlobalResourceSpec_To_proxy_GlobalResourceSpec(in, out, s)
}

func autoConvert_proxy_GlobalResourceSpec_To_v1alpha1_GlobalResourceSpec(in *proxy.GlobalResourceSpec, out *GlobalResourceSpec, s conversion.Scope) error {
	out.TargetCluster = in.TargetCluster
	out.ResourceSelectors = *(*[]ResourceSelector)(unsafe.Pointer(&in.ResourceSelectors))
	return nil
}

// Convert_proxy_GlobalResourceSpec_To_v1alpha1_GlobalResourceSpec is an autogenerated conversion function.
func Convert_proxy_GlobalResourceSpec_To_v1alpha1_GlobalResourceSpec(in *proxy.GlobalResourceSpec, out *GlobalResourceSpec, s conversion.Scope) error {
	return autoConvert_proxy_GlobalResourceSpec_To_v1alpha1_GlobalResourceSpec(in, out, s)
}

func autoConvert_v1alpha1_GlobalResourceStatus_To_proxy_GlobalResourceStatus(in *GlobalResourceStatus, out *proxy.GlobalResourceStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_GlobalResourceStatus_To_proxy_GlobalResourceStatus is an autogenerated conversion function.
func Convert_v1alpha1_GlobalResourceStatus_To_proxy_GlobalResourceStatus(in *GlobalResourceStatus, out *proxy.GlobalResourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_GlobalResourceStatus_To_proxy_GlobalResourceStatus(in, out, s)
}

func autoConvert_proxy_GlobalResourceStatus_To_v1alpha1_GlobalResourceStatus(in *proxy.GlobalResourceStatus, out *GlobalResourceStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_proxy_GlobalResourceStatus_To_v1alpha1_GlobalResourceStatus is an autogenerated conversion function.
func Convert_proxy_GlobalResourceStatus_To_v1alpha1_GlobalResourceStatus(in *proxy.GlobalResourceStatus, out *GlobalResourceStatus, s conversion.Scope) error {
	return autoConvert_proxy_GlobalResourceStatus_To_v1alpha1_GlobalResourceStatus(in, out, s)
}

func autoConvert_v1alpha1_ProxyOptions_To_proxy_ProxyOptions(in *ProxyOptions, out *proxy.ProxyOptions, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_ProxyOptions_To_proxy_ProxyOptions is an autogenerated conversion function.
func Convert_v1alpha1_ProxyOptions_To_proxy_ProxyOptions(in *ProxyOptions, out *proxy.ProxyOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxyOptions_To_proxy_ProxyOptions(in, out, s)
}

func autoConvert_proxy_ProxyOptions_To_v1alpha1_ProxyOptions(in *proxy.ProxyOptions, out *ProxyOptions, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_proxy_ProxyOptions_To_v1alpha1_ProxyOptions is an autogenerated conversion function.
func Convert_proxy_ProxyOptions_To_v1alpha1_ProxyOptions(in *proxy.ProxyOptions, out *ProxyOptions, s conversion.Scope) error {
	return autoConvert_proxy_ProxyOptions_To_v1alpha1_ProxyOptions(in, out, s)
}

func autoConvert_url_Values_To_v1alpha1_ProxyOptions(in *url.Values, out *ProxyOptions, s conversion.Scope) error {
	// WARNING: Field TypeMeta does not have json tag, skipping.

	if values, ok := map[string][]string(*in)["path"]; ok && len(values) > 0 {
		if err := runtime.Convert_Slice_string_To_string(&values, &out.Path, s); err != nil {
			return err
		}
	} else {
		out.Path = ""
	}
	return nil
}

// Convert_url_Values_To_v1alpha1_ProxyOptions is an autogenerated conversion function.
func Convert_url_Values_To_v1alpha1_ProxyOptions(in *url.Values, out *ProxyOptions, s conversion.Scope) error {
	return autoConvert_url_Values_To_v1alpha1_ProxyOptions(in, out, s)
}

func autoConvert_v1alpha1_ResourceSelector_To_proxy_ResourceSelector(in *ResourceSelector, out *proxy.ResourceSelector, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	return nil
}

// Convert_v1alpha1_ResourceSelector_To_proxy_ResourceSelector is an autogenerated conversion function.
func Convert_v1alpha1_ResourceSelector_To_proxy_ResourceSelector(in *ResourceSelector, out *proxy.ResourceSelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceSelector_To_proxy_ResourceSelector(in, out, s)
}

func autoConvert_proxy_ResourceSelector_To_v1alpha1_ResourceSelector(in *proxy.ResourceSelector, out *ResourceSelector, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	return nil
}

// Convert_proxy_ResourceSelector_To_v1alpha1_ResourceSelector is an autogenerated conversion function.
func Convert_proxy_ResourceSelector_To_v1alpha1_ResourceSelector(in *proxy.ResourceSelector, out *ResourceSelector, s conversion.Scope) error {
	return autoConvert_proxy_ResourceSelector_To_v1alpha1_ResourceSelector(in, out, s)
}
