---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmada-proxy
  namespace: karmada-system
  labels:
    app: karmada-proxy
    apiserver: "true"
spec:
  selector:
    matchLabels:
      app: karmada-proxy
      apiserver: "true"
  replicas: 2
  template:
    metadata:
      labels:
        app: karmada-proxy
        apiserver: "true"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: karmada-proxy
          image: swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-proxy:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: k8s-certs
              mountPath: /etc/kubernetes/pki
              readOnly: true
            - name: kubeconfig
              subPath: kubeconfig
              mountPath: /etc/kubeconfig
          command:
            - /bin/karmada-proxy
            - --kubeconfig=/etc/kubeconfig
            - --authentication-kubeconfig=/etc/kubeconfig
            - --authorization-kubeconfig=/etc/kubeconfig
            - --etcd-servers=https://etcd-client.karmada-system.svc.cluster.local:2379
            - --etcd-cafile=/etc/kubernetes/pki/server-ca.crt
            - --etcd-certfile=/etc/kubernetes/pki/karmada.crt
            - --etcd-keyfile=/etc/kubernetes/pki/karmada.key
            - --tls-cert-file=/etc/kubernetes/pki/karmada.crt
            - --tls-private-key-file=/etc/kubernetes/pki/karmada.key
            - --audit-log-path=-
            - --feature-gates=APIPriorityAndFairness=false
            - --audit-log-maxage=0
            - --audit-log-maxbackup=0
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: k8s-certs
          secret:
            secretName: karmada-cert-secret
        - name: kubeconfig
          secret:
            secretName: kubeconfig
---
apiVersion: v1
kind: Service
metadata:
  name: karmada-proxy
  namespace: karmada-system
  labels:
    app: karmada-proxy
    apiserver: "true"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: karmada-proxy
